on:
  push:
    branches:
      - releases/**
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build and Deploy Image
    runs-on: ${{ matrix.os }}
    steps:
      - name: Extract Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Extract Tag Name
        id: tag-name
        run: echo "${{ steps.branch-name.outputs.current_branch }}" | cut -d "/" -f2 | while read line; do echo "::set-output name=tag::$line"; done
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image with Docker
        run: cd ${{ steps.tag-name.outputs.tag }} && docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/strapiv4-node:${{ steps.tag-name.outputs.tag }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Deploy Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/strapiv4-node:${{ steps.tag-name.outputs.tag }}
